modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
    install:
      - mesa-va-drivers
      - git-lfs
      - zsh
      - neovim
      - fzf
      - htop
      - cronie
      - fd-find
      - tldr
      - mpv
      - direnv
      - syncthing
      - NetworkManager-tui
      - keepassxc
      - audacity
      - gron
      - strace
      - rofimoji
      - helvum
      - xrandr
    remove:
      - swaylock
      - swayidle
  - from-file: fume-packages.yml

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.signal.Signal
        - im.riot.Riot  # element-desktop
        - com.github.tchx84.Flatseal

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
