# image will be published to ghcr.io/<user>/<name>
name: fume
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is the only supported tag

modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - fd-find
      - tldr
      - mpv
      - syncthing
      # - greetd
      # - gtkgreet

    remove:
      - swaylock
      - swayidle
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.keepassxc.KeePassXC
        - org.signal.Signal
        - io.github.spacingbat3.webcord
        - com.discordapp.Discord  # webcord doesn't have hardware acceleration.
        - org.audacityteam.Audacity
        - im.riot.Riot  # element-desktop
        # - org.mozilla.firefox
      remove:
        # - org.gnome.eog

  - type: yafti
    custom-flatpaks:
      - Krita: org.kde.krita
      - Ardour: org.ardour.Ardour
      - Godot: org.godotengine.Godot
      - Blender: org.blender.Blender
      - OBS: com.obsproject.Studio
      - Steam: com.valvesoftware.Steam

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
