-- require('lazy-lsp').setup {
--     excluded_servers = {
--         "sqls",
--         "jedi_language_server", "pylsp", -- python, package is manually built upstream.
--         "rls", -- rust, deprecated, rust_analyzer is included
--         "ltex", "zk",  -- markdown
--         "denols", "quick_lint_ls", "tsserver", "flow", "rome", -- javascript
--         "sourcekit", "ccls"  -- cpp
--     },
--     preferred_servers = {
--         python = { "ruff-lisp" },
--         nix = { }, -- I want to use nixd which isn't available.
--     },
--     default_config = {
--         flags = {
--           debounce_text_changes = 150,
--           -- on_attach = on_attach,
--           capabilities = capabilities,
--         },
--     },
-- }
